### ISSUE TITLE
Governance / Permissioning Tracking Issue

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#161]
## Summary

This is a general tracking issue for all the work around governance control of smart contracts
to make a "permissioned" smart contract system possible.

## Problem Definition

The requirements are set forth in the [Cosmos Hub Proposal 25](https://ipfs.io/ipfs/QmbD3bMajQCFmtDmkuRVWhmMWVdN2sK8QP2FoFCz9cjPiC/Cosmos%20Hub%20Proposal_%20CosmWasm%284%29.pdf) which passed, and which we need to implement

Some additional context may be present in the [forum discussion](https://forum.cosmos.network/t/proposal-cosmwasm-on-cosmos-hub/3629)

## Proposal

Exact steps will be defining in smaller issues. This defines the architecture for the whole project. Issues:

- [x] Add Governance Proposals #162 
- [x] Control who can instantiate code #163
- [x]  Control who can upload code #164 

We will add three new governance proposal types to handle the contract lifetime and some more metadata to control the permissioning. Note this does not affect executing contracts, but rather the larger "privileged" lifecycle: upload, instantiate, migrate, which often restricted to an owner.

You should consider the hub governance as root. It can execute any privileged operation on any contract. If you do not want this, then disable those governance proposal types in the binary, so the governance oversight / backdoor (depending on your view) doesn't exist. This means that governance can migrate/burn a contract even if it is marked "immutable". We will add at least three new proposal "content" types. The basics would be `UploadCodeProposal`, `InstantiateContractProposal`, `MigrateContractProposal`. We would also likely want to add an `UpdateAdministratorProposal`, as hub governance may not want to migrate directly but appoint a new committee as administrator to some contested contract after the instantiation (or change the committee responsible).

Beyond the root control, we also want to allow delegating to a subcommittee for quicker oversight. This ends up with upload and instantiate having a permission of Nobody | Somebody(Address) | Anybody and migrate of Nobody | Somebody(Address). The permissions for upload can be stored in module-level Params, which the permission level for instantiate can be stored on the CodeInfo. The Params should list the permission required for uploading and the default permission for instantiating (likely Anybody or Nobody depending on the chain). The CodeInfo permission level can also be set when uploading (overriding Params default).

I believe there is already a generic governance proposal type that can make params changes in the module to update that when needed. If we want to get very extensive, we can also add a message and proposal type to change the permission level of an existing CodeInfo, but that is really quite unnecessary as we could just upload the same wasm again as another CodeInfo but with the desired permissions (this assumes we want to loosen them up).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alpe** [comment]
Very good summary.

> The Params should list the permission required for uploading and the default permission for instantiating (likely Anybody or Nobody depending on the chain).

My first thought was default should be "owner". Somebody invested time and resources to create and upload the contract. We should protect this effort. 

>  If we want to get very extensive, we can also add a message and proposal type to change the permission level of an existing CodeInfo, but that is really quite unnecessary...

There may be the use case where access to the contract's account needs to be granted this way. It is not about the (byte) code only.

A general permission system would make the administrator field obsolete as this would be a permission now. I like it.

**Comment by ethanfrey** [comment]
> My first thought was default should be "owner". Somebody invested time and resources to create and upload the contract. We should protect this effort.

Sounds fair. If unset, only owner (like a custom uniswap module). But they can set to let anyone use it. (Like a generic cw20 module). 

> This is what I you also had in mind, I guess. There could be odd settings like "migrate" set to Somebody with ContractInfo.Admin = nil stored that we should prevent

I am not fully sure I get it.  You want to store the Everybody / Somebody / Nobody enum where? I assume it would be in the same object as (and next to) the field that stores "Somebody" value - those fit together, either in one struct or two fields.
