### ISSUE TITLE
CosmWasm 1.0 tracking issue

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#618]
Points needed:

- [x] https://github.com/CosmWasm/wasmd/pull/617
- [x] https://github.com/CosmWasm/wasmd/issues/601 / https://github.com/CosmWasm/wasmd/pull/608
- [x] https://github.com/CosmWasm/wasmd/issues/584
- [ ] Finally, upgrade to CosmWasm v1.0.0-beta
- [x] Increase gas multiplier by 150_000 to 15_000_000

@webmaster128 please add any other updates needed (pinning, gas, cache info??)
