### ISSUE TITLE
Add Benchmarks to compare with native modules

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/wasmd#635]
BankMsg and ExecuteMsg on cw20-base is the simplest comparison.

Starting with the benchmark in x/bank, let's:

- [x] batch multiple messages per block (eg. 20) (#638)
- [x] use leveldb as a backing store (#639)
- [x] set up the equivalent for cw20 (use the same setup, just different messages) (#638)
- [x] set up significant state first (eg. 10k accounts for both bank and cw20) (#639)
- [x] have bank messages send from different pairs of accounts (not all same sender and same receiver) (#639)
- [ ] Run in go-bencher

**Comment by ethanfrey** [comment]
Basically done. 

One last follow up in #652
